import turtle
def go(x,y):
    t.penup()
    t.goto(x,y)
    t.pendown()
def door():
    t.fillcolor('#1974D2')
    t.begin_fill()
    for i in range(2):
        t.forward(80)
        t.right(90)
        t.forward(35)
        t.right(90)
    t.end_fill()
def block():
    t.fillcolor('#03bafc')
    t.begin_fill()
    for i in range(2):
        t.forward(100)
        t.right(90)
        t.forward(150)
        t.right(90)
    t.end_fill()
    t.fillcolor('#FFFFFF')
    t.begin_fill()
    t.right(45)
    t.penup()
    t.forward(35)
    t.pendown()
    t.left(45)
    for i in range(2):
        t.forward(51)
        t.right(90)
        t.forward(95)
        t.right(90)
    t.end_fill()
def fblock(x,y):
    go(x,y)
    block()
t = turtle.Turtle()
t.fillcolor('#6FA8DC')
t.begin_fill()
for i in range(4):
    t.forward(150)
    t.right(90)
t.end_fill()
go(40,-150)
t.left(90)
door()
go(75,-150)
door()
t.right(90)
fblock(-100,0)
fblock(-200,0)
fblock(-200,150)
fblock(-100,150)
turtle.done()