import turtle
import random as w
t = turtle.Turtle()
t.speed(0)
def mat_dat():
    t.fillcolor('brown')
    t.begin_fill()
    t.penup()
    t.goto(-500,0)
    t.pendown()
    t.forward(1000)
    t.right(90)
    t.forward(500)
    t.right(90)
    t.forward(1000)
    t.right(90)
    t.forward(500)
    t.right(90)
    t.end_fill()
def go(x,y):
    t.penup()
    t.goto(x,y)
    t.pendown()
def door():
    t.left(30)
    t.backward(50)
    t.fillcolor('blue')
    t.begin_fill()
    for i in range(2):
        t.forward(75)
        t.right(90)
        t.forward(50)
        t.right(90)
    t.end_fill()  
def block():
    t.fillcolor('gray')
    t.begin_fill()
    for k in range(2):
        t.forward(300)
        t.right(90)
        t.forward(150)
        t.right(90)
    t.end_fill()
def mountain():
    t.fillcolor('gray')
    t.begin_fill()
    t.left(50)
    t.forward(250)
    t.right(100)
    t.forward(250)
    t.end_fill()
    t.left(50) 
def mai_nha():
    t.begin_fill()
    t.fillcolor('red')
    t.left(30)
    for k in range(2):
        t.forward(180)
        t.right(62)
    t.end_fill()
def tree():
    t.fillcolor('brown')
    t.begin_fill()
    t.penup()
    t.goto(-250,50)
    t.pendown()
    t.left(4.25)
    for k in range(2):
        t.forward(100)
        t.left(90)
        t.forward(50)
        t.left(90)
    t.end_fill()
def tam_giac(y):
    t.fillcolor('green')
    t.begin_fill()
    t.right(90)
    t.forward(25)
    t.right(120)
    for k in range(3):
        t.forward(y)
        t.right(120)
    t.end_fill()
    t.forward(y)
    t.fillcolor('green')
    t.begin_fill()    
    t.left(120)
    t.forward(48)
    t.right(120)
    for k in range(3):
        t.forward(y)
        t.right(120)
    t.end_fill()
    t.forward(y)
    t.fillcolor('green')
    t.begin_fill()
    t.left(120)
    t.forward(48)
    t.right(120)
    for k in range(3):
        t.forward(y)
        t.right(120)
    t.end_fill()
def kinh():
    t.fillcolor('blue')
    t.begin_fill()
    for k in range(4):
        t.forward(35)
        t.right(90)
    t.end_fill()
def mat_troi():
    t.fillcolor('yellow')
    t.begin_fill()
    t.circle(45)
    t.end_fill()

go(-250,0)
mountain()
mat_dat()    
go(-100,100) 
block()
mai_nha()
tree()
tam_giac(100)
go(20,0)
door()
go(-75,50)
kinh()
go(125,50)
kinh()
go(300,225)
mat_troi()
t.hideturtle()
turtle.done()